apiVersion: apps/v1
kind: Deployment
metadata:
  name: range-slider-deployment
spec:
  replicas: 6  # Number of desired replicas
  selector:
    matchLabels:
      app: range-slider
  template:
    metadata:
      labels:
        app: range-slider
    spec:
      containers:
      - name: range-slider
        image: yash5090/range-slider:latest
        ports:
        - containerPort: 5000
